version: '3.8'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
