version: '3.8'

services:
  frontend:
    build:
      context: ./frontend

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
